name             'jmeter'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'Apache 2.0'
description      'Installs/Configures jmeter'
long_description 'Installs/Configures jmeter'
version          '0.1.0'

supports 'centos', '~> 6.5'
supports 'centos', '~> 5.8'
supports 'ubuntu', '= 12.04'
supports 'ubuntu', '= 14.04'

depends 'java'
depends 'ark'
